# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-19 19:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweet',
            old_name='text1',
            new_name='text',
        ),
    ]
