# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-19 19:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0002_auto_20170619_1906'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweet',
            old_name='text',
            new_name='content',
        ),
        migrations.RemoveField(
            model_name='tweet',
            name='text2',
        ),
        migrations.RemoveField(
            model_name='tweet',
            name='text3',
        ),
    ]
