# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-07-26 02:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0009_tweet_liked'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweet',
            old_name='Liked',
            new_name='liked',
        ),
    ]
