# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-07-25 22:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0010_auto_20170725_2159'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweet',
            old_name='Reply',
            new_name='reply',
        ),
    ]
