# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-07-26 03:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0011_auto_20170725_2209'),
        ('tweets', '0010_auto_20170726_0248'),
    ]

    operations = [
    ]
