# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-07-26 03:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0012_merge_20170726_0304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='reply',
        ),
    ]
